name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          registry-url: https://registry.npmjs.org
      - name: install packages
        run: yarn install --frozen-lockfile
      - name: build release package
        run: yarn pack-build
      - name: publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
