name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.15.0
      - run: yarn install --frozen-lockfile
      - run: yarn pack-build
      
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.15.0
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          yarn install --frozen-lockfile
          npm publish
